### ISSUE TITLE
不知为何不能使用

### ISSUE THREAD

**Issue by Orooz** [GreatYYX/dnvod-ad-killer#1]
PS C:\Desktop\dnvod-ad-killer-master> python mitm.py
2018-02-24 21:07:24,121 - INFO - pid:20424 - Starting server on port 8899
2018-02-24 21:08:25,395 - ERROR - pid:20424 - Exception while running the server PicklingError("Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x0000000005C0ADF0>: it's not found as __main__.recvfrom_into",)
Traceback (most recent call last):
  File "mitm.py", line 551, in run
    self.handle(client)
  File "mitm.py", line 567, in handle
    proc.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 754, in save_global
    (obj, module, name))
PicklingError: Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x0000000005C0ADF0>: it's not found as __main__.recvfrom_into
2018-02-24 21:08:25,401 - INFO - pid:20424 - Closing server socket
PS C:\Desktop\dnvod-ad-killer-master> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError

**Comment by GreatYYX** [comment]
@Orooz Thanks for ur report! 我用windows环境测试了一下，使用的http proxy在windows下有点问题。我替换了一个，win10下测试可用。`python mitm2.py`。

**Comment by GreatYYX** [comment]
两个提醒：1.使用前务必清除浏览器缓存（防止浏览器使用缓存了的js文件）。2.proxy的指向从`127.0.0.1`变更为`::1`。

**Comment by Orooz** [comment]
确认有效，谢谢啦！辛苦了！
还有个说明可以添加一下：去广告的时候要关掉ABP或者uBlock之类的插件。

**Comment by Orooz** [comment]
在GreasyFork找到了一个脚本可以去除多瑙广告
https://greasyfork.org/zh-CN/scripts/27013-%E5%A4%9A%E7%91%99%E5%BD%B1%E9%99%A2%E5%8E%BB%E5%B9%BF%E5%91%8A-%E5%A2%9E%E5%BC%BA

再次感谢，还是辛苦啦！

**Comment by GreatYYX** [comment]
@Orooz 这个脚本不错 比挂个代理方便 等脚本失效了再用自己的代理吧哈哈哈
